user:
  # Not keeping discord ID bc it is provided automatically
  base:
    - "username"
  extra:
    - "timezone"
    - "currency"
    - "spreadsheet"

transaction:
  # currency needs to be pulled from user data
  base:
    - "amount"
    - "category"
  extra:
    - "split_percent"
    - "comment"
