user:
  # Not keeping discord ID bc it is provided automatically
  base:
    username: "str"
  extra:
    timezone: "str"
    currency: "str"
    spreadsheet: "str"

transaction:
  # currency needs to be pulled from user data
  base:
    amount: "float"
    category: "str"
  extra:
    split_percent: "float"
    comment: "str"
