user:
  # Not keeping discord ID bc it is provided automatically
  base:
    username: "str"
    spreadsheet: "str"
  extra:
    timezone: "str"
    currency: "str"

transaction:
  # currency needs to be pulled from user data
  base:
    amount: "float"
    category_id: "int"
  extra:
    split_percent: "float"
    comment: "str"

category:
  base:
    category_name: "str"
