register:
  name: "register"
  aliases:
    - "reg"
  help: "Performs user registration, the first command to use this bot."

prepare_sheet:
  name: "prepare_sheet"
  aliases:
    - "ps"
    - "prep_sh"
  help: "Prepares sheet for alfredo to append data to"

whoami:
  name: "whoami"
  aliases:
    - "who"
  help: "Shows user account overview"

update_user_data:
  name: "update_user_data"
  aliases:
    - "uud"
    - "update"
  help: "Updates user account data. Can update either a specific field if called with 2 arguments:
        !uud field data where field is property to update and data is the value to set.
        When called without arguments, iteratively asks data for all the account's fields. Non-deterministic."

get_categories:
  name: "get_categories"
  aliases:
    - "gc"
    - "get_cat"
  help: "Shows categories available for categorizing transactions."

create_category:
  name: "create_category"
  aliases:
    - "nc"
    - "new_cat"
  help: "Creates a new category for categorizing transactions. Admin only command."

update_category:
  name: "update_category"
  aliases:
    - "uc"
    - "upd_cat"
  help: "Updates data of an already exising category. Needs 2 arguments field and data:
        field is property to update and data is the value to set. Cannot be called without arguments.
        Admin only command."

delete_category:
  name: "delete_category"
  aliases:
    - "dc"
    - "del_cat"
  help: "Deletes category with the given id. Admin only command. Use get_categories to fetch category ids."

