register:
  name: "register"
  aliases:
    - "reg"
  help: "Performs user registration, the first command to use this bot."
  btn_label: "Register"

prepare_sheet:
  name: "prepare_sheet"
  aliases:
    - "ps"
    - "prep_sh"
  help: "Prepares sheet for alfredo to append data to"
  btn_label: "Prepare Sheet"

whoami:
  name: "whoami"
  aliases:
    - "who"
  help: "Shows user account overview"
  btn_label: "Show Account Data"

update_user_data:
  name: "update_user_data"
  aliases:
    - "uud"
    - "update"
  help: "Updates user account data. Can update either a specific field if called with 2 arguments:
        !uud field data where field is property to update and data is the value to set.
        When called without arguments, iteratively asks data for all the account's fields. Non-deterministic."
  btn_label: "Update User Data"

get_categories:
  name: "get_categories"
  aliases:
    - "gc"
    - "get_cat"
  help: "Shows categories available for categorizing transactions."

create_category:
  name: "create_category"
  aliases:
    - "nc"
    - "new_cat"
  help: "Creates a new category for categorizing transactions. Admin only command."

update_category:
  name: "update_category"
  aliases:
    - "uc"
    - "upd_cat"
  help: "Updates data of an already exising category. Needs 2 arguments field and data:
        field is property to update and data is the value to set. Cannot be called without arguments.
        Admin only command."

delete_category:
  name: "delete_category"
  aliases:
    - "dc"
    - "del_cat"
  help: "Deletes category with the given id. Admin only command. Use get_categories to fetch category ids."

get_transaction:
  name: "get_transactioin"
  aliases:
    - "gt"
    - "get_tr"
  help: "Fetches a user's ongoing transaction if there is one. Only for registered users."
  btn_label: "Show In Progress Transaction"

new_transaction:
  name: "new_transaction"
  aliases:
    - "tr"
    - "new_tr"
  help: "Creates a new transaction row in alfredo's backend db"
  btn_label: "New Transaction"

delete_transaction:
  name: "delete_transaction"
  aliases:
    - "dt"
    - "del_tr"
  help: "Deletes ongoing (not yet sent to sheets) transaction"
  btn_label: "Delete Transaction"

update_transaction:
  name: "update_transaction"
  aliases:
    - "ut"
    - "upd_tr"
  help: "Updates data of an already exising transaction. Needs 2 arguments field and data:
        field is property to update and data is the value to set. Cannot be called without arguments."

transaction_to_sheet:
  name: "transaction_to_sheet"
  aliases:
    - "tts"
    - "tosheet"
  help: "Sends cached transaction to sheet and removes if from db on success"
  btn_label: "Transaction To Sheet"

show_guide:
  name: "show_guide"
  aliases:
    - "sd"
    - "guide"
  help: "Shows a TLDR of how the bot is meant to be used."
  message:
    - "This is an overview of how alfredo works and how to use it."
    - "Alfredo is a bot helping with personal finances' management.
      It takes in data from commands and sends it to the spreadsheet.
      Spreadsheet id to use is provided by users on registration."
    - "\nA typical workflow could be described as:"
    - "\tComplete user registration (!register)."
    - "\tShare spreadsheet with 'cr-bot228@cryptobot228.iam.gserviceaccount.com' so that alfredo could read / write data there."
    - "\tCreate a transaction (!tr)."
    - "\tFormat your sheet for alfredo to paste transactions there (!ps)."
    - "\tSend transaction to  (!tts)."

# Not actually needed here except for validations
start:
  name: "start"