version: 1

disable_existing_loggers: False

formatters:
  main:
    format: "[%(asctime)s - %(name)s - %(levelname)s - %(funcName)s()]\t %(message)s"
  test:
    format: "[%(asctime)s - %(filename)s - %(levelname)s - %(funcName)s()]\t %(message)s"

filters:
  DiscordErrorFilter:
    (): "alfredo_lib.alfredo_logger.LevelFilter"
    level: "WARNING"
  DiscordFilter:
    (): "alfredo_lib.alfredo_logger.AttributeFilter"
    attr_name: "toDs"
    allow_val: True
    default_val: False
  DiscordSilencer:
    (): "alfredo_lib.alfredo_logger.AttributeFilter"
    attr_name: "IgnoreDs"
    allow_val: False
    default_val: False
  DbFilter:
    (): "alfredo_lib.alfredo_logger.AttributeFilter"
    attr_name: "toDb"
    allow_val: True
    default_val: False


# Add queuelistener handler here
handlers:
  ZZZQListenerHandler:
    (): "alfredo_lib.alfredo_logger.QueueListenerHandler"
    queue: "ext://alfredo_lib.alfredo_logger._LOG_QUEUE"
    handlers:
      - "cfg://handlers.DiscordErrorHandler"
      - "cfg://handlers.DiscordHandler"
      - "cfg://handlers.DbHandler"
      - "cfg://handlers.BackupFileHandler"
  DiscordErrorHandler:
    class: "alfredo_lib.alfredo_logger.DiscordHandler"
    filters:
      - "DiscordErrorFilter"
      - "DiscordSilencer"
  DiscordHandler:
    class: "alfredo_lib.alfredo_logger.DiscordHandler"
    filters:
      - "DiscordFilter"
  DbHandler:
    (): "alfredo_lib.alfredo_logger.DbHandler"
    cache_instance: "ext://alfredo_lib.alfredo_deps.cache"
    filters:
      - "DbFilter"
  BackupFileHandler:
    (): "alfredo_lib.alfredo_logger.BackupFileHandler"
    folder: "./logs"
    file: "alfredo_log.log"
    formatter: "main"
  StreamHandler:
    class: "logging.StreamHandler"
    formatter: "main"
  TestFileHandler:
    (): "alfredo_lib.alfredo_logger.BackupFileHandler"
    folder: "./alfredo_tests/src/test_log"
    file: "alfredo_test_log.log"
    formatter: "test"


loggers:
  alfredo_logger:
    level: "DEBUG"
    handlers:
      - "ZZZQListenerHandler"
      - "StreamHandler"
    propagate: False
  backup_logger:
    level: "DEBUG"
    handlers:
      - "ZZZQListenerHandler"
      - "StreamHandler"
      - "BackupFileHandler"
    propagate: False
  test_logger:
    level: "DEBUG"
    handlers:
      - "TestFileHandler"

    