# TODO ENV differences
cache_path: "cache/alfredo_db.sqlite"

command_prefix: "!"

logging_config: "config/logging_config.yaml"

error_messages:
  missing_input: "Missing mandatory arguments. Check !help and try again"
  prompt_timeout: "Took too long to response. Stopping input collection."

messages:
  transaction_exists: "Found existing transaction. Start a new one (y/n)?. Data:\n {transaction}"

discord:
  project: "ALFREDO BOT"
  users_to_tag:
    PROD:
      - "194543162604126208"
    LOCAL: 
      - "194543162604126208"

main_logger_name: "alfredo_logger"
backup_logger_name: "backup_logger"
test_logger_name: "test_logger"

user_input_schemas: "config/schemas/user_inputs.yaml"

float_precision: 4

input_prompt_timeout: 30